export const LIGHT: Record<string, string> = {
  '--app-bg':              '#F8F8FF',
  '--app-surface':         '#FFFFFF',
  '--app-surface-hover':   '#F5F3FF',
  '--app-accent-bg':       '#E0D9FF',
  '--app-accent-soft':     '#EDE9FE',
  '--app-accent-tint':     '#F0EEFF',
  '--app-text-primary':    '#080830',
  '--app-text-heading':    '#18186A',
  '--app-text-deep':       '#101048',
  '--app-text-secondary':  '#4848A0',
  '--app-text-accent':     '#383898',
  '--app-text-strong':     '#222280',
  '--app-text-muted':      '#5E5E9C',
  '--app-text-faint':      '#7878A8',
  '--app-text-ghost':      '#A6A6D4',
  '--app-text-step':       '#1E1E78',
  '--app-border':          '#C8C8E2',
  '--app-border-strong':   '#BDBDDB',
  '--app-border-subtle':   '#CDCDE8',
  '--app-border-muted':    '#B2B2D2',
  '--app-border-accent':   '#9494D4',
  '--app-border-alt':      '#A4A4D2',
  '--app-border-light':    '#C6C6E0',
  '--app-nav-bg':          '#FFFFFF',
  '--app-preview-overlay': 'rgba(238,238,255,0.97)',
};

export const DARK: Record<string, string> = {
  '--app-bg':              '#0B0B18',
  '--app-surface':         '#17172B',
  '--app-surface-hover':   '#1F1F38',
  '--app-accent-bg':       '#2A1D6E',
  '--app-accent-soft':     '#1E1460',
  '--app-accent-tint':     '#150E48',
  '--app-text-primary':    '#EEEEFF',
  '--app-text-heading':    '#D0D0F8',
  '--app-text-deep':       '#E0E0FF',
  '--app-text-secondary':  '#B0B0E0',
  '--app-text-accent':     '#A0A0D8',
  '--app-text-strong':     '#C0C0F0',
  '--app-text-muted':      '#9090C8',
  '--app-text-faint':      '#7070A8',
  '--app-text-ghost':      '#505090',
  '--app-text-step':       '#C0C0F0',
  '--app-border':          '#2C2C48',
  '--app-border-strong':   '#3A3A5C',
  '--app-border-subtle':   '#242438',
  '--app-border-muted':    '#303050',
  '--app-border-accent':   '#5050A0',
  '--app-border-alt':      '#484890',
  '--app-border-light':    '#26263E',
  '--app-nav-bg':          '#0E0E1E',
  '--app-preview-overlay': 'rgba(8,8,20,0.97)',
};
